apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: laravel
type: application
version: 1.6.0
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ^12.12.10
  - name: mysql
    condition: mysql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ^9.12.3
  - name: redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: ^18.1.0
  - name: soketi
    condition: soketi.enabled
    repository: https://helm.soketi.app
    version: ^1.0.2
