ingress:
  enabled: false
postgresql:
  enabled: false
mysql:
  enabled: false
redis:
  enabled: false
soketi:
  enabled: false
cronjobs:
  enabled: false
migration:
  enabled: true
workers:
  enabled: true
