{{- if and .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.fullname" . }}-migration
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.migration.annotations | nindent 4 }}
spec:
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    spec:
     {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "laravel.fullname" . }}-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        {{- if .Values.volumeMounts }}
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        {{- end }}
          - name: scripts
            mountPath: "/mnt/scripts"
        resources:
{{- toYaml .Values.migration.resources | nindent 12 }}
        command:
          - sh
          - -c
          - {{ .Values.migration.cmd }}
      restartPolicy: Never
      volumes:
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
        - name: scripts
          configMap:
            name: {{ include "laravel.fullname" . }}-scripts
            defaultMode: 0777
{{- end }}
