{{- if .Values.workers.enabled }}
{{- range .Values.workers.items }}
  {{- $autoscalingEnabled := false }}
  {{- if hasKey . "autoscaling" }}
    {{- if hasKey .autoscaling "enabled" }}
      {{- $autoscalingEnabled = .autoscaling.enabled }}
    {{- else }}
      {{- $autoscalingEnabled = $.Values.workers.autoscaling.enabled }}
    {{- end }}
  {{- else }}
    {{- $autoscalingEnabled = $.Values.workers.autoscaling.enabled }}
  {{- end }}
  {{- if $autoscalingEnabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPod Autoscaler
metadata:
  name: {{ regexReplaceAll "_" .name "-" }}-worker-hpa
  labels:
    {{- include "laravel.labels" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "workerName" .name) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ regexReplaceAll "_" .name "-" }}-worker
  minReplicas: {{ .autoscaling.minReplicas | default $.Values.workers.autoscaling.minReplicas }}
  maxReplicas: {{ .autoscaling.maxReplicas | default $.Values.workers.autoscaling.maxReplicas }}
  metrics:
    {{- if or .autoscaling.targetCPUUtilizationPercentage $.Values.workers.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.targetCPUUtilizationPercentage | default $.Values.workers.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if or .autoscaling.targetMemoryUtilizationPercentage $.Values.workers.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.targetMemoryUtilizationPercentage | default $.Values.workers.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
