apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.fullname" . }}
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.encryptionKey | default "4d91f20854a10f0aabcfcac22070f12f" | b64enc | quote }}
  jwt-secret: {{ .Values.jwtSecret | default "a1f8ebe0fe5bec75c1bf6cc3ce2b793ee52d288bf57511242ba074ff290d68fb" | b64enc | quote }}